# ============================================================
# Repositories
# ============================================================
# format: name:clone_url

REPOS=(
    "tmux:https://github.com/moecly/tmux-config.git"
    "zsh:https://github.com/moecly/zsh-config.git"
    "nvim:https://github.com/moecly/nvim-config.git"
    "alacritty:https://github.com/moecly/alacritty-config.git"
    "keyd:https://github.com/moecly/keyd-config.git"
    "niri:https://github.com/moecly/niri-config.git"
    "kitty:https://github.com/moecly/kitty-config.git"
    "swaylock:https://github.com/moecly/swaylock-config.git"
    "fuzzel:https://github.com/moecly/fuzzel-config.git"
    "fontconfig:https://github.com/moecly/fontconfig-config.git"
    "wlogout:https://github.com/moecly/wlogout-config.git"
    "DankMaterialShell:https://github.com/moecly/dms-shell-config.git"
)
